task_tracker/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'auth#temp_page'
  get 'auth/:provider/callback', to: 'auth#create'
  get '/signin', to: 'auth#index'

  resources :tasks, only: [:index, :new, :create]
  get '/tasks/my', to: 'tasks#my'
  get '/tasks/shuffle', to: 'tasks#shuffle'
end

task_tracker/app/models/account.rb
class Account < ApplicationRecord
  has_many :tasks
end

task_tracker/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :account
end

task_tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update]

  def index
    @account = current_account
    @tasks = Task.includes(:account).all
  end

  def new
  end

  def my
    @account = current_account
    @tasks = Task.includes(:account).where(account: current_account)

    render :index
  end

  def create
    employee = Account.find(Account.where(role: 'employee').pluck(:id).sample)
    task = Task.create!(
      description: params[:description],
      jira_id: params[:jira_id],
      account: employee
    )

    # HOMEWORK 3
    event = {
      event_id: SecureRandom.uuid,
      event_version: 2,
      event_time: Time.now.to_s,
      producer: 'auth_service',
      event_name: 'TaskCreated',
      data: {
        public_id: task.public_id,
        description: task.description,
        jira_id: task.jira_id,
        account_id: task.account.public_id
      }
    }

    result = SchemaRegistry.validate_event(event, 'tasks.created', version: 2)

    if result.success?
      Karafka.producer.produce_async(
        topic: 'tasks',
        payload: event.to_json
      )

      redirect_to :tasks
    else
      # handle error
    end
  end

  def edit
  end

  def update
    task.update(status: params[:status])

    # HOMEWORK 3
    event = {
      event_id: SecureRandom.uuid,
      event_version: 1,
      event_time: Time.now.to_s,
      producer: 'auth_service',
      event_name: 'TaskCompleted',
      data: { public_id: task.public_id, account_id: task.account.public_id }
    }

    result = SchemaRegistry.validate_event(event, 'tasks.completed', version: 1)

    if result.success?
      Karafka.producer.produce_async(
        topic: 'tasks',
        payload: event.to_json
      )
    end
  end

  def shuffle
    employees = Account.where(role: 'employee').pluck(:id)
    Task.find_each do |task|
      Task.update!(account_id: employees.sample)

      event = {
        event_id: SecureRandom.uuid,
        event_version: 2,
        event_time: Time.now.to_s,
        producer: 'auth_service',
        event_name: 'TaskAssigned',
        data: {
          public_id: task.public_id,
          description: task.description,
          jira_id: task.jira_id,
          account_id: task.account.public_id
        }
      }

      result = SchemaRegistry.validate_event(event, 'tasks.assigned', version: 1)

      if result.success?
        Karafka.producer.produce_async(
          topic: 'tasks',
          payload: event.to_json
        )
      end
    end
  end

  private

  def current_account
    @current_account ||= Account.find_by(public_id: session['account']['info']['public_id'])
  end

  def set_account
    @task = Task.find(params[:id])
  end
end

task_tracker/app/helpers/auth_helper.rb
module AuthHelper
end

task_tracker/app/helpers/tasks_helper.rb
module TasksHelper
end

task_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

task_tracker/app/views/tasks/index.html.erb
<h1>Tasks</h1>

<br />
<p><%= link_to 'New task', new_task_path %></p>
<br />

<p>
  <% if @account.role == 'admin' %>
    <%= button_to 'Shuffle tasks', tasks_shuffle_path, method: :post %>
  <% end %>
</p>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>public_id</th>
      <th>account</th>
      <th>description</th>
      <th>status</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.public_id %></td>
        <td><%= task.account.full_name %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

task_tracker/app/views/tasks/new.html.erb
<%= form_with url: tasks_path, method: :post do |form| %>
  <div>
    <p>Description</p>
    <%= form.text_field(:description) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>